name = "bitter-river-06ec"
main = "src/index.js"         # or index.js depending on your code
compatibility_date = "2025-06-06"

[[r2_buckets]]
binding = 'daughter'
bucket_name = 'tongtong'

[[r2_buckets]]
binding = 'mummy'
bucket_name = 'suyee'
preview_bucket_name = 'suyee'
